import type { Metadata } from "next";
import localFont from "next/font/local";
import { Toaster } from "react-hot-toast";
import { LandingLayout } from "@/components/layout/landing";

import "./globals.css";

const IranSans = localFont({
  src: "../assets/fonts/iran-sans/iransans-regular.woff",
  variable: "--font-iran-sans",
});

export const metadata: Metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      dir="rtl"
      lang="fa"
      className={`${IranSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <LandingLayout>{children}</LandingLayout>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
